// src/context/LanguageContext.js
import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("ta"); // "ta" | "en"
  const toggle = () => setLang(l => l === "ta" ? "en" : "ta");
  return (
    <LanguageContext.Provider value={{ lang, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

// UI strings for both languages
export const UI = {
  ta: {
    appName: "TNBC",
    appSub: "தவக்கால பயண தடிமி",
    logout: "வெளி",
    back: "← பின்",
    admin: "நிர்வாக",
    welcome: "தவக்கால பயணம்",
    subtitle: "Lenten Journey 2026 · 40 நாட்கள்",
    org: "TNBC Commission for Charismatic Renewal and Proclamation",
    newReg: "புதிய பதிவு",
    loginAgain: "மீண்டும் உள்நுழை",
    register: "புதிய பதிவு",
    login: "உள்நுழைக",
    adminLogin: "நிர்வாக உள்நுழைவு",
    namePlaceholder: "உங்கள் பெயர்",
    passwordPlaceholder: "கடவுச்சொல்",
    submit: "உள்நுழைக",
    alreadyReg: "ஏற்கனவே உள்ளீர்களா?",
    notReg: "புதியவரா?",
    progress: "மொத்த முன்னேற்றம்",
    days: "/40 நாட்கள்",
    selectDay: "நாட்களை தேர்ந்தெடுக்கவும்",
    full: "முழு", partial: "பகுதி", pending: "பாக்கி", today: "இன்று",
    doLabel: "செய்யுங்கள்",
    giveLabel: "கொடுங்கள்",
    avoidLabel: "விட்டுவிடுங்கள்",
    dayLabel: "நாள்",
    todayLabel: "இன்றைய நாள் ✦",
    leaderboard: "🏆 சமூக முன்னேற்ற பட்டியல்",
    lbTitle: "🏆 சமூக முன்னேற்றம்",
    fullMark: "முழு", partialMark: "பகுதி",
    youLabel: "(நீங்கள்)",
    loading: "ஏற்றுகிறது...",
    noData: "இன்னும் யாரும் பங்கேற்கவில்லை",
    adminTitle: "நிர்வாக பலகை",
    tabs: ["கண்ணோட்டம்", "உறுப்பினர்கள்", "நினைவூட்டல்", "தரவரிசை"],
    statLabels: ["மொத்த உறுப்பினர்கள்", "செயலில் உள்ளவர்கள்", "சராசரி முழு நாட்கள்"],
    refresh: "புதுப்பி ↻",
    members: "உறுப்பினர்கள் பதிவாகியுள்ளனர்",
    joinedAt: "அன்று சேர்ந்தார்",
    remove: "நீக்கு",
    reminderTitle: "அனைவருக்கும் நினைவூட்டல் அனுப்பு",
    reminderPlaceholder: "உங்கள் செய்தியை இங்கே உள்ளிடுக...",
    send: "அனுப்பு",
    prevReminders: "முந்தைய நினைவூட்டல்கள்",
    confirmRemove: "இந்த உறுப்பினரை நீக்கவா?",
    toastWelcome: (name) => `வரவேற்கிறோம், ${name}! 🙏`,
    toastBack: (name) => `மீண்டும் வரவேற்கிறோம், ${name}! 🙏`,
    toastNameTaken: "இந்தப் பெயர் ஏற்கனவே உள்ளது",
    toastNotFound: "பெயர் காணவில்லை. முதலில் பதிவு செய்யவும்.",
    toastWrongPw: "தவறான கடவுச்சொல்",
    toastAdminWrong: "தவறான நிர்வாக கடவுச்சொல்",
    toastRemoved: "உறுப்பினர் நீக்கப்பட்டார்",
    toastReminder: "நினைவூட்டல் அனுப்பப்பட்டது ✓",
    toastError: "பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
  },
  en: {
    appName: "TNBC",
    appSub: "Lenten Journey Tracker",
    logout: "Logout",
    back: "← Back",
    admin: "Admin",
    welcome: "Lenten Journey",
    subtitle: "Lenten Journey 2026 · 40 Days",
    org: "TNBC Commission for Charismatic Renewal and Proclamation",
    newReg: "New Registration",
    loginAgain: "Login Again",
    register: "New Registration",
    login: "Login",
    adminLogin: "Admin Login",
    namePlaceholder: "Your name",
    passwordPlaceholder: "Password",
    submit: "Login",
    alreadyReg: "Already registered?",
    notReg: "New here?",
    progress: "Overall Progress",
    days: " / 40 days",
    selectDay: "Select a day",
    full: "Full", partial: "Partial", pending: "Pending", today: "Today",
    doLabel: "Do",
    giveLabel: "Give",
    avoidLabel: "Avoid",
    dayLabel: "Day",
    todayLabel: "Today ✦",
    leaderboard: "🏆 View Community Leaderboard",
    lbTitle: "🏆 Community Progress",
    fullMark: "Full", partialMark: "Partial",
    youLabel: "(You)",
    loading: "Loading...",
    noData: "No participants yet",
    adminTitle: "Admin Dashboard",
    tabs: ["Overview", "Members", "Reminders", "Leaderboard"],
    statLabels: ["Total Members", "Active Members", "Avg. Full Days"],
    refresh: "Refresh ↻",
    members: "members registered",
    joinedAt: "joined on",
    remove: "Remove",
    reminderTitle: "Send a reminder to everyone",
    reminderPlaceholder: "Type your message here...",
    send: "Send",
    prevReminders: "Previous Reminders",
    confirmRemove: "Remove this member?",
    toastWelcome: (name) => `Welcome, ${name}! 🙏`,
    toastBack: (name) => `Welcome back, ${name}! 🙏`,
    toastNameTaken: "This name is already taken",
    toastNotFound: "Name not found. Please register first.",
    toastWrongPw: "Incorrect password",
    toastAdminWrong: "Incorrect admin password",
    toastRemoved: "Member removed",
    toastReminder: "Reminder sent ✓",
    toastError: "An error occurred. Please try again.",
  },
};
